### ISSUE TITLE
bad port

### ISSUE THREAD

**Issue by patizon** [jlasti/secmon#68]
![image](https://cloud.githubusercontent.com/assets/11499945/25358960/9c5ca840-2943-11e7-8d8b-a0f24818fc40.png)
toto je dest. porta nie source

**Comment by st3lly** [comment]
chyba je v rulach pre normalizator
src=$6 **spt**=$10 outcome=success app=SSHv2 destinationServiceName=sshd duser=$5 
nie spt ale dpt ak je to destination cize si si nahlasil vlastnu chybu :D
